// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FT.Web.Site.Controllers
{
    public partial class HotelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HotelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HotelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Resultado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Resultado);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HotelController Actions { get { return MVC.Hotel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Hotel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Hotel";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Resultado = "Resultado";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Resultado = "Resultado";
        }


        static readonly ActionParamsClass_Resultado s_params_Resultado = new ActionParamsClass_Resultado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Resultado ResultadoParams { get { return s_params_Resultado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Resultado
        {
            public readonly string hotel = "hotel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Resultado = "Resultado";
            }
            public readonly string Index = "~/Views/Hotel/Index.cshtml";
            public readonly string Resultado = "~/Views/Hotel/Resultado.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HotelController : FT.Web.Site.Controllers.HotelController
    {
        public T4MVC_HotelController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ResultadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FT.Web.Site.Models.Hotel hotel);

        public override System.Web.Mvc.ActionResult Resultado(FT.Web.Site.Models.Hotel hotel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Resultado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hotel", hotel);
            ResultadoOverride(callInfo, hotel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
