// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FT.Web.Site.Controllers
{
    public partial class IngressosController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public IngressosController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected IngressosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TagSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoadGrid()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadGrid);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public IngressosController Actions { get { return MVC.Ingressos; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Ingressos";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Ingressos";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string TagSearch = "TagSearch";
            public readonly string LoadGrid = "LoadGrid";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string TagSearch = "TagSearch";
            public const string LoadGrid = "LoadGrid";
        }


        static readonly ActionParamsClass_TagSearch s_params_TagSearch = new ActionParamsClass_TagSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagSearch TagSearchParams { get { return s_params_TagSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagSearch
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_LoadGrid s_params_LoadGrid = new ActionParamsClass_LoadGrid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadGrid LoadGridParams { get { return s_params_LoadGrid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadGrid
        {
            public readonly string ingresso = "ingresso";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string LoadGrid = "LoadGrid";
            }
            public readonly string Index = "~/Views/Ingressos/Index.cshtml";
            public readonly string LoadGrid = "~/Views/Ingressos/LoadGrid.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_IngressosController : FT.Web.Site.Controllers.IngressosController
    {
        public T4MVC_IngressosController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void TagSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        public override System.Web.Mvc.ActionResult TagSearch(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            TagSearchOverride(callInfo, term);
            return callInfo;
        }

        partial void LoadGridOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FT.Web.Site.Models.Ingresso ingresso);

        public override System.Web.Mvc.ActionResult LoadGrid(FT.Web.Site.Models.Ingresso ingresso)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadGrid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ingresso", ingresso);
            LoadGridOverride(callInfo, ingresso);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
